version: "3"

services:
  db:
    container_name: padel-db
    restart: always
    image: postgres:14-alpine
    ports:
      - 6432:5432 # target:source  (ojo el port adentro de la red de docker es 5432 )  
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}      
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_WEB_USER=${POSTGRES_WEB_USER}
      - POSTGRES_WEB_PASS=${POSTGRES_WEB_PASS}
    volumes:
      - data_vol:/var/lib/postgresql/data
      - ./db/sql_scripts/create_tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/sql_scripts/insert_data.sql:/docker-entrypoint-initdb.d/2.sql                  
      - ./db/shell_scripts/init_user.sh:/docker-entrypoint-initdb.d/init_user.sh    
  api:
    container_name: padel-api
    build:
      context: .
      dockerfile: ./api/api.dockerfile    
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      db:
        condition: service_started
    environment:             
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
    data_vol:
      name: padel-db-volume
      driver: local